### ISSUE TITLE
Invalid route name

### ISSUE THREAD

**Issue by faf** [Mibew/mibew-operator-status-plugin#1]
One should change the name of the route defined [here](https://github.com/everyx/mibew-operator-status-plugin/blob/master/src/routing.yml#L1).

At the moment it is impossible to use the plugin with the original Mibew Boilerplate. Also, the current name of the route is confusing.

**Comment by everyx** [comment]
ok, I'll change the route name

> the current name of the route is confusing

Is there any suggestion? I'm not a professional developer.

will `everyx_operator_status` as the name is much more better?
`<AUTHOR_NAME>_<PLUGIN_NAME_WITH_UNDERLINE>`
