### ISSUE TITLE
Operator status plugin not listing

### ISSUE THREAD

**Issue by yurinativo** [Mibew/mibew-operator-status-plugin#11]
I downloaded the Operator Status plugin from github and from sourceforge.
I unziped both on plugin folder (mibew\plugin\)
I got this structure:
```
mibew\plugins\OperatorStatus\Controller\OperatorStatusController.php
mibew\plugins\OperatorStatus\LICENSE
mibew\plugins\OperatorStatus\Plugin.php
mibew\plugins\OperatorStatus\README.md
mibew\plugins\OperatorStatus\routing.yml
```

Then I edited the mibew\configs\config.yml.
The plugin section look like this:
```
# Plugins
plugins:
    "Mibew:OperatorStatus"
```

But when I navigate to the plugins page (http://[site]/mibew/operator/plugin) the plugin list is empty.

What I did wrong?

**Comment by yurinativo** [comment]
Just to be sure, I tried to unzip the plugin inside the folder "plugins" and "plugin".
And the zip downloaded from github I put inside the folder "operator-status".
The zip downloaded from sourceforge I put inside the folder "OperatorStatus".

Now I have this structure:

```
[mibew folder]\plugin\OperatorStatus\*
[mibew folder]\plugin\operator-status\*
[mibew folder]\plugins\OperatorStatus\*
[mibew folder]\plugins\operator-status\*
```

The plugin page still show no plugins

**Comment by faf** [comment]
The installation process is **clearly** described in the `README.txt` file. You're not supposed to alter the structure of the directories. The relative structure of the directories should be `plugins/Mibew/Mibew/Plugin/OperatorStatus/<files of the plugin>`. And it is exactly the very same structure that is in the release archive.

**Comment by yurinativo** [comment]
Yeah, that´s solved the problem.
Thanks
